# Generated by Django 3.0.6 on 2020-05-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200528_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
